export const COLORS = {
  primary: "#9966CC",
  lightPrimary: "#dfc8f6",
  // primary: "#2EB5FA",
  pink: "#D81E5B",
  light: "#FDFFFC",
  dark: "#1E1E1E",
  dark700: "#524B6B",
  text: "#150B3D",
  title: "#0D0140",
  white: "#fff",
  yellow: "#FF9228",
  error: "#ff0d10",
  orange: "#ffe7cc",
};

export const CALANDER_THEME = {
  selectedDayBackgroundColor: COLORS.primary,
  arrowColor: COLORS.primary,
  textSectionTitleColor: COLORS.dark,
  todayTextColor: COLORS.dark,
  monthTextColor: COLORS.primary,
  indicatorColor: COLORS.primary,
  textDayFontFamily: "DMSansMedium",
  textMonthFontFamily: "DMSansSemiBold",
  textDayHeaderFontFamily: "DMSansMedium",
  textMonthFontWeight: "bold",
  textDayHeaderFontWeight: "300",
  textMonthFontSize: 16,
  textDayHeaderFontSize: 14,
  textDisabledColor: "#b3b3b3",
};
