export const LANGUAGES: string[] = [
  "हिन्दी",
  "English",
  "मराठी",
  "ગુજરાતી",
  "ਪੰਜਾਬੀ",
  "বাংলা",
  "తెలుగు",
  "தமிழ்",
  "ಕನ್ನಡ",
  "ଓଡ଼ିଆ",
  "മലയാളം",
  "অসমীয়া",
  "मैथिली",
  "भीली/भीलोडी",
];

export const STATES: string[] = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];
