export const SLOGANS = [
  '"Good health" is not something we can buy. However, it can be an extremely valuable savings account.',
  "Health citizens are the greatest assets any country can have.",
  "Health is a blessing in one's life that only the sick person can see.",
  "Losing Health is Losing all the wealth you have.",
  "When you lose fat, you against winning fosgai and are illness. Burn the fat and forget about the rest.",
  "Your health is the key that unlocks your prosperous future.",
  "A healthy lifestyle is a step towards a better health and meaningful existence everyday.",
  "Wellness is not a one time achievement; it's a daily practice.",
  "Your body is the only place where you have to live. So embrace and treat it with care and respect.",
  "Prioritising self care is the beginning of your health journey.",
  '"Nourish Today, Thrive Tomorrow: Celebrating Wellness Every Day on World Health Day!"',
  '"Empower Wellness, Embrace Vitality: World Health Day, A Global Commitment."',
  '"Wellness Unites Us: World Health Day, Building Stronger Communities, Together."',
  '"From Self-Care to Global Care: World Health Day, Igniting a Healthier World."',
  '"Health in Harmony: Let\'s Tune into Wellness this World Health Day and Beyond!"',
  "Be protective towards your health.",
  "Nourish your soul heal your body.",
  "Stay strong stay healthy stay platinum.",
  "Health is your jwellary.",
  "Join the movement for Wealthier World with Healthier Body.",
  "Every Step Towards Health is a step towards Wealth.",
  "Choose Health, Choose Happiness.",
  "Small Steps: Bright future, Big Impact. Good Health.",
  "Use sanitary napkin keep your health clean.",
  "Take small steps towards your health everyday.",
  "Body health is the access to assets.",
  "Be protective towards your health.",
  "Good health helps to achieve wealth.",
  "Physical fitness is the first requisite of happiness.",
  "Health is a blessing in one's life that only the sick person can see!",
  "We often lose health when we are busy accumulating wealth!",
  "In health there is FREEDOM, it frees you from ILLNESS.",
  "A healthy body is a guest - chamber for the soul; a sick body is a prison.",
  "Replace the CARBS in your life with HERBS.",
  "Make me sweat, make me hotter- your obese body.",
  "Greeny-leafy vegGreeny-leafy veg pillars for your after age. pillars for your after age.",
  "Stop being delulu and take prompt solulu for your health.",
  "Toxic relationship as well as toxic food both are dangerous to your health.",
  "Pain due to yoga is better than regretting pain and expenses due to Riots.",
  "It's a virtue of smart, to protect the heart from emotional and painful dart.",
  "The food you eat is as per your will because your body is not a public dughill.",
  "Fast food, won't do any good.",
  "Be the magnet for positive thoughts, and say to anxiety and depression get lost.",
  "Your health is your true wealth.",
  "Your body deserves the best; Don't compromise on health.",
  "Fight disease with ease; Maintain Health and Peace.",
  "Embrace wholesome living, not only for longevity but for a life brimming with vitality and joy.",
  "Together, let's weave the fabric of a healthier tomorrow through the threads of awareness and prevention today.",
  "Stop earing unhealthy food, make your future healthy and good.",
  "In this world of stress, nobody has time for themselves, atleast with positive thoughts, improve your mental health.",
  "If you will hesitate to tell you will never get well.",
  "Your wellness can kill the illness.",
  "Follow healthy habit and see the magic.",
  "Balance in diet balance in life.",
  "Health is an art not everyone can master.",
  "Want to fail the germs then top the hygiene.",
  "Stay fit and tell the bacteria to take a chill pill.",
  "Cleanliness is the key to healthiness.",
  "Renew your health subscription before you receive a prescription.",
  "Crack the crab(cancer) before it cracks you!",
  "Exercise regularly to prevent early demise.",
  "Overall diet is for physical health and so is Morale diet for mental health!",
  "Feel your emotions to heal your trauma.",
  "Mental health is the biggest wealth, A peaceful mind will become your strength.",
  "Keep your health fit & sunny, it's worth more than wealth and money.",
  "Proteins, Minerals & Vitamins are nature's gift, Have a balanced diet & keep yourself fit.",
  "If you don't have time for fitness, you will be forced to take out time for your illness.",
  "There are hundreds of ways to become wealthy but discipline is only way to be healthy.",
  "Never work out because you have started hating your body but because you have started loving it.",
  "Mental illness is nothing to be ashamed of, but stigma and bias shame us all.",
  "If alcohol is your choice today then medicine will be your only option tomorrow.",
  "Discipline, motivation, hardwork, consistency - key words for your health.",
  "Healthy lifestyle is the secret of my energy.",
  "Take walks for a healthy future,Don't be a slave to your comfort",
  "When it comes to your health, never compromise",
  "Exercise, sleep and nutritious food should be your goal ,because in healthy life it has a very big role.",
  "A good laugh and a good slip are the best cures in the doctor's book.",
  "A Healthy Person Can achieve High Success than one who is not well.",
  "Diseases No Entry , Doctors No Entry ,hence We are Hale and Healthy",
  "Body is our temple, keep it clean and safe with you.",
  "Yoga is the artwork of awareness on the canvas of body , mind and soul.",
  "Health is the soul that animates all the enjoyments of life, which fade and are tasteless without it.",
  "A nation with healthy citizens can well always be very active in every field.",
  "In the heart of Jagannath, find solace and surrender to divine love.",
  "Cleanliness builds Healthy society , All Nations together Should make a Great Effort for a Healthy Society.",
  "Will power and Patience are the Two important Secrets of Senior Citizens Health.",
  "Children are healthy as they are ACTIVE, Adults are not healthy as they are INACTIVE.",
  "Health and Wealth Should be the two Phases of the same Coin for Successful journey.",
  "Yoga and meditation are the ways spoken , which makes the world of good mental health open.",
  "Maintaining a healthy and active life is a major factor, If you want to stay safe from cancer!",
  "Wash your hands and keep them clean, It increases your chances of living a life evergreen!",
  "Taking care of your mental health doesn't make you selfish, Instead a great asset to society, one to truly cherish!",
  "Regular health checkups aer'nt a waste of money, Instead a way to ensure the safety of you and your family.",
  "An apple a day keeps the doctor away.",
  "Good Environment , Better Food ,Best exercise Leads To The Best Life.",
  "A nation with healthy citizens can well always be very active in every field.",
  "A good laugh and a good slip are the best cures in the doctor's book.",
  "Cleanliness builds Healthy society , All Nations together Should make a Great Effort for a Healthy Society.",
  "Health and Wealth Should be the two Phases of the same Coin for Successful journey.",
  "Children are healthy as they are ACTIVE, Adults are not healthy as they are INACTIVE.",
  "Health and Wealth Should be the two Phases of the same Coin for Successful journey.",
  "Health and Wealth Should be the two Phases of the same Coin for Successful journey.",
  "An apple a day keeps the doctor away.",
  "Good Environment , Better Food ,Best exercise Leads To The Best Life.",
  "Health and Wealth Should be the two Phases of the same Coin for Successful journey.",
  "Health and Wealth Should be the two Phases of the same Coin for Successful journey.",
  "An apple a day keeps the doctor away.",
  "Smoking and drinking alcohol might give temporary pleasure, but are you ready to face its repercussions as a lifelong terror?",
  "Maintaining a healthy and active life is a major factor, If you want to stay safe from cancer!",
  "You can't enjoy wealth if you're not in good health.",
  "Healthy food for wealthy Mood.",
  "An apple a day keeps the doctor away.",
  "Maintaining a healthy and active life is a major factor, If you want to stay safe from cancer!",
];

// "निरोगी आरोग्य आहे आपला अमूल्य ठेवा, या धकाधकीच्या जीवनात याचा विसर न पडावा.",
// "नियमित व्यायाम आणि संतुलित आहार, हाच आहे सुखी , आनंदी जीवनाचा आधार.",
// "धावपळीचे या दुनियेत आरोग्यासाठी वेळ काढा , योगा आणि कसरत करून आजारपण टाळा.",
// "अच्छी सेहत रखना ये, हमारा अधिकार हैं!",
// "मनुष्य के जीवन में, स्वास्थ्य से बडा कोई धन नहीं!",
// "स्वस्थ शरीर तब रहेगा, जब स्वस्थ मन होगा!",
// "स्वस्थ जीवन जीने का मार्ग, स्वस्थ आहार और व्यायाम!",
// "स्वास्थ्य आपकी खुशियों का मूल है, इसे संभाल कर रखें!",
// "जेवे हातातुन देवे हातातुन मग काळजी घ्यावी हाताची स्वच्छ होऊन.",
// "आयुष्यातला बँक बॅलन्स संपला तरी चालेल, पण आरोग्याची validity संपू देऊ नका.",
// "निरोगी आरोग्याला, उज्वल भविष्याची साथ!",
// "सौंदर्या बरोबर, आरोग्याचे कर्तव्य देखील जपा!",
// "आरोग्याच्या नवसंकल्पनेचा करूया स्वीकार निरोगी राहण्याचा मला अधिकार..!",
// "निळं निळं पाणी, हिरवं हिरवं शिवार; माझे आरोग्य, माझा अधिकार!",
// "नित्य करावी कसरत, असावे आरोग्याचे परिपत्रक, निळ निळ पाणी हिरव शिवार, माझे आरोग्य माझा आधिकार !",
// "स्वच्छ हवा घेण्याचा, शुध्द पाणी पिण्याचा, संतुलित आहार खाण्याचा, आहे आधिकार मला निरोगी गुणवत्तापूर्ण घरात राहण्याचा !",
// "नसावा अंगी आळस, असावी अंगणी तुळस ...अधिकार नाही तो याचा त्याचा, माझा आरोग्य अधिकार आहे तो माझा !",
// "आरोग्य नाही ती संपदा आहे, माझे आरोग्य माझा आधिकार आहे !",
// "मानवी हक्क आरोग्याचा अधिकार आहे प्रतेकाचा !"
// "अच्छा स्वास्थ्य दे स्वतंत्रता, बुरा स्वास्थ्य दे बंधन।",
// "रोज व्यायाम, संतुलित भोजन। स्वस्थ्य जीवन, प्रसन्न तन - मन।",
// "अच्छा स्वास्थ्य, उगता सूरज। बुरा स्वास्थ्य, ढलती शाम।",
// "अच्छे स्वास्थ्य से बढ़कर कोई सुख ना है, बुरे स्वास्थ्य से बढ़कर कोई दुख ना है।",
// "संतुलित भोजन दे आरोग्यता, कसरत दे तन को विश्राम। पूर्ण निद्रा दे उद्दिप्तता, यही है अच्छे स्वास्थ्य के आयाम।",
// "आरोग्य हा धन आहे, सुखी जीवनाचा मार्ग आहे!",
// "आरोग्याला प्राथमिकता द्या, आनंदाला प्राथमिकता द्या.",
// "आरोग्य निवड, स्वस्थ निवड, सुखी आवाज!",
// "भोजनोत्तर फळांचा ग्रास, यांबवेल आरोग्याचा हास!",
// "नित्य कसरत असे जिथे। आरोग्य उत्तम असे तिथे",
// "स्वस्थ असेल शरीर तर , संभव होईल प्रत्येक काम. स्वास्थ असेल सोबत तर, तय करू प्रत्येक मुकाम.",
// "नित्य करूया दहा सूर्यनमस्कार , दुरुस्त शरीरासाठी होईल चमत्कार.",
// "पालेभाज्या घ्या मुखी ,आरोग्य ठेवा सुखी.",
// "नित्य कसरत असे जिथे,आरोग्य उत्तम असे तिथे.",
// "सकाळ संध्याकाळी करूया योग, नाही जवळ येणार काहीही रोग.",
// "जेवे हातातुन देवे हातातुन मग काळजी घ्यावी हाताची स्वच्छ होऊन.",
